name: Check markdown links

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Every month
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.lycheeignore'
      - '.github/workflows/linkcheck.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.lycheeignore'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          save-always: 'true'
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-
      - name: Lychee Checker
        uses: lycheeverse/lychee-action@v2.3.0
        id: lychee
        with:
          fail: true
          args: '--accept 200,204,429 --verbose --no-progress --cache --max-cache-age 1d content/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
